#!/bin/bash

# Activate the conda environment
source ./condaEnvironmentAudio.sh

# Audio is in mydataset/video.wav
REFERENCE_AUDIO="mydataset/video.wav"
TEXT_TO_SPEAK="This is a cloned voice generated by OpenVoice."
OUTPUT_DIR="outputs"

# Check if checkpoints exist
if [ ! -d "OpenVoice/checkpoints" ]; then
    echo "Error: OpenVoice checkpoints not found."
    echo "Please download them and extract to OpenVoice/checkpoints"
    echo "See OpenVoice/docs/USAGE.md for instructions."
    exit 1
fi

echo "Running OpenVoice cloning..."
python runOpenvoice.py --reference_file "$REFERENCE_AUDIO" --text "$TEXT_TO_SPEAK" --output_dir "$OUTPUT_DIR"

